### PR TITLE
avformat: be compatible with all version ffmpeg

### LINKED ISSUE #73: Compile failure on Ubuntu Trusty (14.04) with AVFORMAT
With `--enable-avformat`, libyami-utils fails to compile using the Ubuntu Trusty provided libav*-dev packages.  It compiles fine on Ubuntu Xenial (16.04) and Yakkety (16.10).  Configure should detect the proper version of libav* required to compile.

> ../tests/decodeinputavformat.cpp:106:5: error: 'AV_CODEC_ID_H265' was not declared in this scope
> AV_CODEC_ID_H265, YAMI_MIME_H265,
> ^
> ../tests/decodeinputavformat.cpp: In member function 'virtual bool DecodeInputAvFormat::getNextDecodeUnit(VideoDecodeBuffer&)':
> ../tests/decodeinputavformat.cpp:127:34: error: 'av_packet_unref' was not declared in this scope
> av_packet_unref(&m_packet);
> ^
> ../tests/decodeinputavformat.cpp: In destructor 'virtual DecodeInputAvFormat::~DecodeInputAvFormat()':
> ../tests/decodeinputavformat.cpp:153:34: error: 'av_packet_unref' was not declared in this scope
> av_packet_unref(&m_packet);
> ^
> make[2]: *** [../tests/grid-decodeinputavformat.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ../tests/decodeinputavformat.cpp:106:5: error: 'AV_CODEC_ID_H265' was not declared in this scope
> AV_CODEC_ID_H265, YAMI_MIME_H265,
> ^
> ../tests/decodeinputavformat.cpp: In member function 'virtual bool DecodeInputAvFormat::getNextDecodeUnit(VideoDecodeBuffer&)':
> ../tests/decodeinputavformat.cpp:127:34: error: 'av_packet_unref' was not declared in this scope
> av_packet_unref(&m_packet);
> ^
> ../tests/decodeinputavformat.cpp: In destructor 'virtual DecodeInputAvFormat::~DecodeInputAvFormat()':
> ../tests/decodeinputavformat.cpp:153:34: error: 'av_packet_unref' was not declared in this scope
> av_packet_unref(&m_packet);
> ^
> make[2]: *** [../tests/decodeinputavformat.o] Error 1

### PR DESCRIPTION
**Pull request by wudping**
The old version ffmpeg does't support HEVC, and does't have the API
av_packet_unref(). So add some MACRO to make yami-utils can be compatible
with all the version of FFMPEG.

to fix #73 

Signed-off-by: wudping <dongpingx.wu@intel.com>

### CODE REVIEW

**Comment by wudping** [comment]
please help to review, thanks in advance.

File: tests/decodeinputavformat.cpp [hunk 1]
```diff
@@ -103,7 +103,9 @@ static const MimeEntry MimeEntrys[] = {
 #endif
 
     AV_CODEC_ID_H264, YAMI_MIME_H264,
+#if (__LIBAVCODEC_NEW__)
```
Comment (xuguangxin) [inline tests/decodeinputavformat.cpp]: Please check which version of bring HEVC and define the macro as 
```
#if LIBAVCODEC_VERSION_INT > AV_VERSION_INT(54, 40, 0)		
     AV_CODEC_ID_VP9, YAMI_MIME_VP9,
  #endif
```

File: tests/decodeinputavformat.cpp [hunk 2]
```diff
@@ -124,7 +126,11 @@ bool DecodeInputAvFormat::getNextDecodeUnit(VideoDecodeBuffer &inputBuffer)
     int ret;
     while (1) {
         //free old packet
+#if (__LIBAVCODEC_NEW__)
```
Comment (xuguangxin) [inline tests/decodeinputavformat.cpp]: Please check which version will rename av_free_packet, and use following define at start

```
#if LIBAVCODEC_VERSION_INT < AV_VERSION_INT(xxxx)		
#define av_packet_unref av_free_packet
 #endif
```

File: configure.ac [hunk 3]
```diff
@@ -246,6 +246,10 @@ fi
 
 if test "$enable_avformat" = "yes"; then
     PKG_CHECK_MODULES(LIBAVFORMAT,  [libavformat libavcodec libavutil])
+    PKG_CHECK_MODULES([LIBAVCODEC_VERSION], [libavcodec >= 55.39.100],
```
Comment (xuguangxin) [inline configure.ac]: no need this if you following suggestion list below

**Comment by wudping** [comment]
hi @xuguangxin , the HEVC and API av_packet_unref are brought by version 55.39.100;
